services:
  nicegui:
    image: zauberzeug/nicegui:latest
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app # mounting local app directory
    depends_on:
      - search_embeddings
  jupyter:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    container_name: jupyter-gpu
    ports:
      - "8888:8888"
    volumes:
      - ./data/:/opt/data/
      - ./models/:/opt/models/
    environment:
      - DATA_DIR=/opt/data
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HF_HOME=opt/models/huggingface/

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  # Create another service for Search Embeddings API
  search_embeddings:
    image: search_embeddings:latest
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: search_embeddings
    ports:
      - "8000:8000"
    volumes:
      - ./data/:/opt/data/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    environment:
      - DATA_DIR=/opt/data
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
