FROM tensorflow/tensorflow:latest-gpu
ENV VIRTUAL_ENV=/opt/venv

# Create virtual environment and install dependencies
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY ./requirements.txt /opt/app/requirements.txt
RUN pip install -r /opt/app/requirements.txt 
RUN pip install "fastapi[standard]"
COPY . /opt/app
WORKDIR /opt/app
# Expose port
EXPOSE 5000

# Activate venv and run the API
CMD ["fastapi", "run", "main.py"]
